# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 507)
        MainWindow.setStyleSheet("* {\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    color: #176B87;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#centralwidget { \n"
"    background-color: #EEF5FF;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stack = QtWidgets.QStackedWidget(self.centralwidget)
        self.stack.setObjectName("stack")
        self.main_window = QtWidgets.QWidget()
        self.main_window.setStyleSheet(".QPushButton{   \n"
"     transition: 1s;\n"
"\n"
"    color: #176B87;\n"
"    border: 3px solid #176B87;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 17px;\n"
"    background-color : #B4D4FF;\n"
"    padding: 10px;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"}\n"
".QPushButton:hover { \n"
"    color: #627254;\n"
"    background-color: #86B6F6;\n"
"    border: 4px solid #176B87;\n"
"}\n"
"\n"
"#main_window {\n"
"    background-color: #EEF5FF;\n"
"}\n"
"\n"
"#start_btn:disabled{\n"
"    background-color: #EEF5FF;\n"
"    border-color: #9CB8C1;\n"
"    color: #9CB8C1;\n"
"}")
        self.main_window.setObjectName("main_window")
        self.gridLayout = QtWidgets.QGridLayout(self.main_window)
        self.gridLayout.setObjectName("gridLayout")
        self.start_btn = QtWidgets.QPushButton(self.main_window)
        self.start_btn.setEnabled(False)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout.addWidget(self.start_btn, 3, 1, 1, 1)
        self.get_template_btn = QtWidgets.QPushButton(self.main_window)
        self.get_template_btn.setObjectName("get_template_btn")
        self.gridLayout.addWidget(self.get_template_btn, 7, 1, 1, 1)
        self.icon_lbl = QtWidgets.QLabel(self.main_window)
        self.icon_lbl.setEnabled(True)
        self.icon_lbl.setMouseTracking(False)
        self.icon_lbl.setText("")
        self.icon_lbl.setScaledContents(False)
        self.icon_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_lbl.setWordWrap(False)
        self.icon_lbl.setObjectName("icon_lbl")
        self.gridLayout.addWidget(self.icon_lbl, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 4, 1, 1, 1)
        self.choose_file_btn = QtWidgets.QPushButton(self.main_window)
        self.choose_file_btn.setStyleSheet("")
        self.choose_file_btn.setObjectName("choose_file_btn")
        self.gridLayout.addWidget(self.choose_file_btn, 5, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem8, 6, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 3)
        self.gridLayout.setRowStretch(4, 1)
        self.stack.addWidget(self.main_window)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet(".QPushButton{   \n"
"     transition: 1s;\n"
"\n"
"    color: #176B87;\n"
"    border: 2px solid #176B87;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 16px;\n"
"    background-color : #B4D4FF;\n"
"    padding: 8px;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    \n"
"}\n"
".QPushButton:hover { \n"
"    color: #627254;\n"
"    background-color: #86B6F6;\n"
"    border: 3px solid #176B87;\n"
"}\n"
"\n"
"#answer_lineedit {\n"
"    border: 2px solid #176B87;\n"
"    border-radius: 5px;\n"
"    max-height: 35px;\n"
"    font-size: 16px;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    color: #176B87;\n"
"}\n"
"\n"
"#answer_lbl {\n"
"    color: #176B87;\n"
"\n"
"}\n"
"\n"
"#page_2 {\n"
"    background-color: #EEF5FF;\n"
"}")
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.next_btn = QtWidgets.QPushButton(self.page_2)
        self.next_btn.setObjectName("next_btn")
        self.gridLayout_2.addWidget(self.next_btn, 5, 1, 1, 1)
        self.question_lbl = QtWidgets.QLabel(self.page_2)
        self.question_lbl.setText("")
        self.question_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.question_lbl.setWordWrap(True)
        self.question_lbl.setObjectName("question_lbl")
        self.gridLayout_2.addWidget(self.question_lbl, 0, 0, 1, 2)
        self.get_hint_btn = QtWidgets.QPushButton(self.page_2)
        self.get_hint_btn.setObjectName("get_hint_btn")
        self.gridLayout_2.addWidget(self.get_hint_btn, 5, 0, 1, 1)
        self.answer_lbl = QtWidgets.QLabel(self.page_2)
        self.answer_lbl.setStyleSheet("width: 50px")
        self.answer_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.answer_lbl.setObjectName("answer_lbl")
        self.gridLayout_2.addWidget(self.answer_lbl, 4, 0, 1, 1)
        self.answer_lineedit = QtWidgets.QLineEdit(self.page_2)
        self.answer_lineedit.setObjectName("answer_lineedit")
        self.gridLayout_2.addWidget(self.answer_lineedit, 4, 1, 1, 1)
        self.hint_lbl = QtWidgets.QLabel(self.page_2)
        self.hint_lbl.setLineWidth(1)
        self.hint_lbl.setText("")
        self.hint_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.hint_lbl.setWordWrap(True)
        self.hint_lbl.setObjectName("hint_lbl")
        self.gridLayout_2.addWidget(self.hint_lbl, 2, 0, 1, 2)
        self.stack.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setEnabled(True)
        self.page.setToolTip("")
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet("#page { \n"
"    background-color: #EEF5FF;\n"
"}\n"
"\n"
"#results_table {\n"
"    border: 2px solid #176B87;\n"
"    gridline-color: #176B87;\n"
"}\n"
"#results_table::section{\n"
"    border: 1px solid #176B87;\n"
"}\n"
".QHeaderView{\n"
"    background-color: #EEF5FF;\n"
"}\n"
".QHeaderView::section{\n"
"    background-color: #EEF5FF;\n"
"    color: #176B87;\n"
"}\n"
"#results_table:disabled {\n"
"    color: #176B87;\n"
"    background-color: #EEF5FF;\n"
"}\n"
"\n"
".QPushButton{   \n"
"     transition: 1s;\n"
"    color: #176B87;\n"
"    border: 2px solid #176B87;\n"
"    font-family:\'Montserrat\', sans-serif;\n"
"    text-transform: uppercase;\n"
"    text-align: center;\n"
"    line-height: 1;\n"
"    font-size: 14px;\n"
"    background-color : #B4D4FF;\n"
"    padding: 7px;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    max-width: 200px;\n"
"}\n"
".QPushButton:hover { \n"
"    color: #627254;\n"
"    background-color: #86B6F6;\n"
"    border: 4px solid #176B87;\n"
"}")
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.result_lbl = QtWidgets.QLabel(self.page)
        self.result_lbl.setObjectName("result_lbl")
        self.gridLayout_3.addWidget(self.result_lbl, 0, 0, 1, 1)
        self.back_to_menu_btn = QtWidgets.QPushButton(self.page)
        self.back_to_menu_btn.setEnabled(True)
        self.back_to_menu_btn.setObjectName("back_to_menu_btn")
        self.gridLayout_3.addWidget(self.back_to_menu_btn, 0, 1, 1, 1)
        self.results_table = QtWidgets.QTableWidget(self.page)
        self.results_table.setEnabled(True)
        self.results_table.setToolTipDuration(-1)
        self.results_table.setAutoFillBackground(False)
        self.results_table.setAutoScroll(True)
        self.results_table.setTabKeyNavigation(False)
        self.results_table.setProperty("showDropIndicator", False)
        self.results_table.setDragDropOverwriteMode(False)
        self.results_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.results_table.setShowGrid(True)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(0)
        self.results_table.setRowCount(0)
        self.results_table.horizontalHeader().setCascadingSectionResizes(True)
        self.results_table.horizontalHeader().setHighlightSections(True)
        self.results_table.horizontalHeader().setSortIndicatorShown(False)
        self.results_table.horizontalHeader().setStretchLastSection(False)
        self.results_table.verticalHeader().setVisible(False)
        self.results_table.verticalHeader().setCascadingSectionResizes(True)
        self.results_table.verticalHeader().setHighlightSections(True)
        self.results_table.verticalHeader().setSortIndicatorShown(False)
        self.results_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.results_table, 1, 0, 1, 2)
        self.stack.addWidget(self.page)
        self.verticalLayout.addWidget(self.stack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setText(_translate("MainWindow", "начать"))
        self.get_template_btn.setText(_translate("MainWindow", "Получить шаблон"))
        self.choose_file_btn.setText(_translate("MainWindow", "Выбрать"))
        self.next_btn.setText(_translate("MainWindow", "Ввести ответ"))
        self.get_hint_btn.setText(_translate("MainWindow", "Показать подсказку"))
        self.answer_lbl.setText(_translate("MainWindow", "Ответ:"))
        self.result_lbl.setText(_translate("MainWindow", "Результат"))
        self.back_to_menu_btn.setText(_translate("MainWindow", "вернуться в главное меню"))
